In [1]:
#import packages
from pytrends.request import TrendReq
import csv
import time
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import numpy as np
from plotnine import *
import seaborn as sns
import matplotlib.pyplot as plt
import missingno as msno # https://github.com/ResidentMario/missingno

In [2]:
#Connecting to Google (WORKS)
pytrends = TrendReq(hl='en-US', tz=360)

In [3]:
#Building Payload
kw_list = ["economia", "Previdência", "Bolsa Família", "Desemprego", "Plano Governo"]
#segmented for national and most populous states in each region
geos = ["BR","BR-AM", "BR-BA", "BR-MS", "BR-SP", "BR-RS"] 
timeframe = ['all']

In [4]:
#Build Trends Over Time for Brazil
pytrends.build_payload(
    kw_list, 
    cat=0, 
    timeframe='all', 
    geo=geos[0])

BR_trends = pytrends.interest_over_time()

In [22]:
filter_BR = BR_trends.loc[BR_trends.index.isin(['2006-11-01','2006-12-01','2010-11-01','2010-12-01','2014-11-01','2014-12-01','2018-11-01','2018-12-01'])]
filter_BR

,economia,Previdência,Bolsa Família,Desemprego,Plano Governo,isPartial
date,,,,,,
2006-11-01,55,11,2,12,2,False
2006-12-01,24,8,1,9,1,False
2010-11-01,33,4,1,14,1,False
2010-12-01,16,4,1,11,0,False
2014-11-01,24,4,2,17,1,False
2014-12-01,13,3,2,18,0,False
2018-11-01,23,6,5,16,2,False
2018-12-01,13,4,5,15,1,False

In [6]:
#Build Trends Over Time for Amazonas
pytrends.build_payload(
    kw_list, 
    cat=0, 
    timeframe='all', 
    geo=geos[1])

AM_trends = pytrends.interest_over_time()

In [7]:
filter_AM = AM_trends.loc[AM_trends.index.isin(['2006-11-01','2010-11-01','2014-11-01', '2018-11-01'])]
filter_AM

,economia,Previdência,Bolsa Família,Desemprego,Plano Governo,isPartial
date,,,,,,
2006-11-01,0,0,0,0,0,False
2010-11-01,0,0,0,0,0,False
2014-11-01,11,1,0,4,1,False
2018-11-01,9,2,3,6,1,False

In [8]:
#Build Trends Over Time for Bahia
pytrends.build_payload(
    kw_list, 
    cat=0, 
    timeframe='all', 
    geo=geos[2])

BA_trends = pytrends.interest_over_time()

In [9]:
filter_BA = BA_trends.loc[BA_trends.index.isin(['2006-11-01','2010-11-01','2014-11-01', '2018-11-01'])]
filter_BA

,economia,Previdência,Bolsa Família,Desemprego,Plano Governo,isPartial
date,,,,,,
2006-11-01,41,11,4,6,0,False
2010-11-01,20,1,1,7,0,False
2014-11-01,17,2,1,12,0,False
2018-11-01,15,3,6,11,1,False

In [10]:
#Build Trends Over Time for Mato Grosso do Sul
pytrends.build_payload(
    kw_list, 
    cat=0, 
    timeframe='all', 
    geo=geos[3])

MS_trends = pytrends.interest_over_time()

In [11]:
filter_MS = MS_trends.loc[BA_trends.index.isin(['2006-11-01','2010-11-01','2014-11-01', '2018-11-01'])]
filter_MS

,economia,Previdência,Bolsa Família,Desemprego,Plano Governo,isPartial
date,,,,,,
2006-11-01,16,8,0,8,0,False
2010-11-01,21,0,0,0,0,False
2014-11-01,9,2,1,4,0,False
2018-11-01,12,1,1,4,1,False

In [12]:
#Build Trends Over Time for Sao Paulo
pytrends.build_payload(
    kw_list, 
    cat=0, 
    timeframe='all', 
    geo=geos[4])

SP_trends = pytrends.interest_over_time()

In [13]:
filter_SP = SP_trends.loc[SP_trends.index.isin(['2006-11-01','2010-11-01','2014-11-01', '2018-11-01'])]
filter_SP

,economia,Previdência,Bolsa Família,Desemprego,Plano Governo,isPartial
date,,,,,,
2006-11-01,50,10,2,8,2,False
2010-11-01,28,2,1,17,0,False
2014-11-01,18,3,1,15,1,False
2018-11-01,18,5,3,14,1,False

In [14]:
#Build Trends Over Time for Rio Grande do Sul
pytrends.build_payload(
    kw_list, 
    cat=0, 
    timeframe='all', 
    geo=geos[5])

RS_trends = pytrends.interest_over_time()

In [15]:
filter_RS = RS_trends.loc[RS_trends.index.isin(['2006-11-01','2010-11-01','2014-11-01', '2018-11-01'])]
filter_RS

,economia,Previdência,Bolsa Família,Desemprego,Plano Governo,isPartial
date,,,,,,
2006-11-01,44,8,4,8,2,False
2010-11-01,26,4,2,10,0,False
2014-11-01,18,3,1,12,0,False
2018-11-01,18,3,3,13,1,False

In [16]:
filter_BR = filter_BR.drop('isPartial', 1)
filter_AM = filter_AM.drop('isPartial', 1)
filter_BA = filter_BA.drop('isPartial', 1)
filter_MS = filter_MS.drop('isPartial', 1)
filter_SP = filter_SP.drop('isPartial', 1)
filter_RS = filter_RS.drop('isPartial', 1)